// Generated by Haxe 4.3.3
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	window.document.getElementById("addNode").onclick = function(_) {
		Main.addNode();
	};
	window.document.getElementById("exportJson").onclick = function(_) {
		window.document.getElementById("output").textContent = Main.exportJSON();
	};
	window.document.getElementById("exportXml").onclick = function(_) {
		window.document.getElementById("output").textContent = Main.exportXML();
	};
	Main.render();
};
Main.addNode = function() {
	Main.nodes.push({ id : "node_" + Main.nodes.length, text : "", choices : [], flags : []});
	Main.render();
};
Main.addChoice = function(nodeIndex) {
	var node = Main.nodes[nodeIndex];
	var text = window.prompt("選択肢テキスト:","");
	if(text == null || text == "") {
		return;
	}
	var next = window.prompt("遷移先ノードID:","");
	if(next == null) {
		next = "";
	}
	var condStr = window.prompt("条件フラグ（例: hasKey,!metNPC）:","");
	var conditions = [];
	if(condStr != null && condStr != "") {
		var _g = 0;
		var _g1 = condStr.split(",");
		while(_g < _g1.length) {
			var s = StringTools.trim(_g1[_g++]);
			if(s == "") {
				continue;
			}
			var required = true;
			var flag = s;
			if(StringTools.startsWith(s,"!")) {
				required = false;
				flag = HxOverrides.substr(s,1,null);
			}
			conditions.push({ flag : flag, required : required});
		}
	}
	node.choices.push({ text : text, next : next, conditions : conditions});
	Main.render();
};
Main.updateNodeText = function(i,value) {
	Main.nodes[i].text = value;
};
Main.updateNodeFlags = function(i,value) {
	var flags = [];
	var _g = 0;
	var _g1 = value.split(",");
	while(_g < _g1.length) {
		var s = StringTools.trim(_g1[_g++]);
		if(s != "") {
			flags.push(s);
		}
	}
	Main.nodes[i].flags = flags;
};
Main.render = function() {
	var container = window.document.getElementById("editor");
	container.innerHTML = "";
	var _g = 0;
	var _g1 = Main.nodes.length;
	while(_g < _g1) {
		var i = [_g++];
		var node = Main.nodes[i[0]];
		var box = window.document.createElement("div");
		box.style.border = "1px solid #ccc";
		box.style.padding = "8px";
		box.style.marginBottom = "8px";
		var title = window.document.createElement("h2");
		title.textContent = node.id;
		box.appendChild(title);
		var textLabel = window.document.createElement("div");
		textLabel.textContent = "テキスト:";
		box.appendChild(textLabel);
		var textarea = [window.document.createElement("textarea")];
		textarea[0].value = node.text;
		textarea[0].rows = 3;
		textarea[0].style.width = "100%";
		textarea[0].oninput = (function(textarea,i) {
			return function(_) {
				Main.updateNodeText(i[0],textarea[0].value);
			};
		})(textarea,i);
		box.appendChild(textarea[0]);
		var flagLabel = window.document.createElement("div");
		flagLabel.textContent = "到達時に立てるフラグ（カンマ区切り）:";
		flagLabel.style.marginTop = "6px";
		box.appendChild(flagLabel);
		var flagInput = [window.document.createElement("input")];
		flagInput[0].type = "text";
		flagInput[0].style.width = "100%";
		flagInput[0].value = node.flags.join(", ");
		flagInput[0].oninput = (function(flagInput,i) {
			return function(_) {
				Main.updateNodeFlags(i[0],flagInput[0].value);
			};
		})(flagInput,i);
		box.appendChild(flagInput[0]);
		var choiceTitle = window.document.createElement("div");
		choiceTitle.textContent = "選択肢:";
		choiceTitle.style.marginTop = "8px";
		box.appendChild(choiceTitle);
		var _g2 = 0;
		var _g3 = node.choices;
		while(_g2 < _g3.length) {
			var c = _g3[_g2];
			++_g2;
			var cDiv = window.document.createElement("div");
			cDiv.style.borderTop = "1px dashed #aaa";
			cDiv.style.marginTop = "4px";
			cDiv.style.paddingTop = "4px";
			var cText = "\"" + c.text + "\" → " + (c.next == "" ? "(終端)" : c.next);
			if(c.conditions.length > 0) {
				var condStr = [];
				var _g4 = 0;
				var _g5 = c.conditions;
				while(_g4 < _g5.length) {
					var cond = _g5[_g4];
					++_g4;
					condStr.push((cond.required ? "" : "!") + cond.flag);
				}
				cText += " [条件: " + condStr.join(", ") + "]";
			}
			cDiv.textContent = cText;
			box.appendChild(cDiv);
		}
		var addChoiceBtn = window.document.createElement("button");
		addChoiceBtn.textContent = "選択肢追加";
		addChoiceBtn.onclick = (function(i) {
			return function(_) {
				Main.addChoice(i[0]);
			};
		})(i);
		box.appendChild(addChoiceBtn);
		container.appendChild(box);
	}
};
Main.exportJSON = function() {
	return JSON.stringify(Main.nodes,null,"\t");
};
Main.exportXML = function() {
	var b_b = "";
	b_b = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
	b_b = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" + "<dialogues>\n";
	var _g = 0;
	var _g1 = Main.nodes;
	while(_g < _g1.length) {
		var node = _g1[_g];
		++_g;
		b_b += Std.string("  <node id=\"" + node.id + "\">\n");
		b_b += Std.string("    <text>" + Main.escapeXml(node.text) + "</text>\n");
		if(node.flags.length > 0) {
			b_b += "    <flags>\n";
			var _g2 = 0;
			var _g3 = node.flags;
			while(_g2 < _g3.length) b_b += Std.string("      <flag>" + Main.escapeXml(_g3[_g2++]) + "</flag>\n");
			b_b += "    </flags>\n";
		}
		if(node.choices.length > 0) {
			b_b += "    <choices>\n";
			var _g4 = 0;
			var _g5 = node.choices;
			while(_g4 < _g5.length) {
				var c = _g5[_g4];
				++_g4;
				b_b += Std.string("      <choice next=\"" + Main.escapeXmlAttr(c.next) + "\">\n");
				b_b += Std.string("        <text>" + Main.escapeXml(c.text) + "</text>\n");
				if(c.conditions.length > 0) {
					b_b += "        <conditions>\n";
					var _g6 = 0;
					var _g7 = c.conditions;
					while(_g6 < _g7.length) {
						var cond = _g7[_g6];
						++_g6;
						b_b += Std.string("          <condition flag=\"" + Main.escapeXmlAttr(cond.flag) + "\" required=\"" + (cond.required == null ? "null" : "" + cond.required) + "\" />\n");
					}
					b_b += "        </conditions>\n";
				}
				b_b += "      </choice>\n";
			}
			b_b += "    </choices>\n";
		}
		b_b += "  </node>\n";
	}
	b_b += "</dialogues>\n";
	return b_b;
};
Main.escapeXml = function(s) {
	return s.split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;");
};
Main.escapeXmlAttr = function(s) {
	return Main.escapeXml(s).split("\"").join("&quot;");
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.startsWith = function(s,start) {
	if(s.length >= start.length) {
		return s.lastIndexOf(start,0) == 0;
	} else {
		return false;
	}
};
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
Main.nodes = [];
Main.main();
})({});
