name: Build DialogueFlow-Editor

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3

      - name: Build tool.js
        run: haxe build.hxml

      - name: Upload tool.js artifact
        uses: actions/upload-artifact@v4
        with:
          name: tool-js
          path: tool.js
